<a href="https://colab.research.google.com/github/nikhilongo/Playground-datasets/blob/main/spaceship_titanic/spaceship_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df.shape

(8693, 11)

In [ ]:
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    8492 non-null   object 
 1   CryoSleep     8476 non-null   object 
 2   Destination   8511 non-null   object 
 3   Age           8514 non-null   float64
 4   VIP           8490 non-null   object 
 5   RoomService   8512 non-null   float64
 6   FoodCourt     8510 non-null   float64
 7   ShoppingMall  8485 non-null   float64
 8   Spa           8510 non-null   float64
 9   VRDeck        8505 non-null   float64
 10  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(4)
memory usage: 687.8+ KB


In [ ]:
[df[col].value_counts() for col in df]

[PassengerId
 9280_02    1
 0001_01    1
 0002_01    1
 0003_01    1
 0003_02    1
           ..
 0020_04    1
 0020_05    1
 0020_06    1
 0022_01    1
 0024_01    1
 Name: count, Length: 8693, dtype: int64,
 HomePlanet
 Earth     4602
 Europa    2131
 Mars      1759
 Name: count, dtype: int64,
 CryoSleep
 False    5439
 True     3037
 Name: count, dtype: int64,
 Cabin
 G/734/S     8
 B/11/S      7
 F/1411/P    7
 B/82/S      7
 G/981/S     7
            ..
 G/543/S     1
 B/106/P     1
 G/542/S     1
 F/700/P     1
 G/559/P     1
 Name: count, Length: 6560, dtype: int64,
 Destination
 TRAPPIST-1e      5915
 55 Cancri e      1800
 PSO J318.5-22     796
 Name: count, dtype: int64,
 Age
 24.0    324
 18.0    320
 21.0    311
 19.0    293
 23.0    292
        ... 
 72.0      4
 78.0      3
 79.0      3
 77.0      2
 76.0      2
 Name: count, Length: 80, dtype: int64,
 VIP
 False    8291
 True      199
 Name: count, dtype: int64,
 RoomService
 0.0       5577
 1.0        117
 2.0         7

In [ ]:
df.drop(columns=['PassengerId','Cabin','Name'],inplace=True)

In [ ]:
df.isnull().sum().reset_index()

index    0
0     HomePlanet  201
1      CryoSleep  217
2    Destination  182
3            Age  179
4            VIP  203
5    RoomService  181
6      FoodCourt  183
7   ShoppingMall  208
8            Spa  183
9         VRDeck  188
10   Transported    0

In [ ]:
df[df['CryoSleep'].isnull()]

HomePlanet CryoSleep  Destination   Age    VIP  RoomService  FoodCourt  \
92        Earth       NaN  TRAPPIST-1e   2.0  False          0.0        0.0   
98        Earth       NaN  TRAPPIST-1e  27.0  False          0.0        0.0   
104      Europa       NaN  TRAPPIST-1e  40.0  False          0.0      331.0   
111        Mars       NaN  TRAPPIST-1e  26.0  False          0.0        0.0   
152       Earth       NaN  TRAPPIST-1e  58.0  False          0.0      985.0   
...         ...       ...          ...   ...    ...          ...        ...   
8620     Europa       NaN  55 Cancri e  44.0  False          0.0        0.0   
8651      Earth       NaN  TRAPPIST-1e   8.0  False          0.0        0.0   
8664      Earth       NaN  TRAPPIST-1e  32.0  False          0.0        0.0   
8675      Earth       NaN  TRAPPIST-1e  44.0  False       1030.0     1015.0   
8687     Europa       NaN  TRAPPIST-1e  30.0  False          0.0     3208.0   

      ShoppingMall   Spa  VRDeck  Transported  
92             0.0   0.0     0.0         True  
98           570.0   2.0   131.0        False  
104            0.0   0.0  1687.0        False  
111            0.0   0.0     NaN         True  
152            0.0   5.0     0.0         True  
...            ...   ...     ...          ...  
8620           0.0   0.0     0.0         True  
8651           0.0   0.0     0.0        False  
8664           0.0   0.0     0.0         True  
8675           0.0  11.0     NaN         True  
8687           0.0   2.0   330.0         True  

[217 rows x 11 columns]

In [ ]:
col=[col for col in df if df[col].dtypes=='float64']
for i in col:
    df[i].fillna(df[i].mean(),inplace=True)

<ipython-input-25-a625f6ec4303>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mean(),inplace=True)


In [ ]:
col1=[col1 for col1 in df if df[col1].dtypes=='object']
for i in col1:
    df[i].fillna(df[i].mode()[0],inplace=True)

<ipython-input-27-6322970d6208>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)
<ipython-input-27-6322970d6208>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[i].fillna(df[i].mode()[0],inplace=True)


In [ ]:
df.isnull().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

In [ ]:
df1 = pd.get_dummies(df,columns=col1,drop_first=True)

In [ ]:
y = df['Transported']

In [ ]:
x = df1.drop(columns=['Transported'])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
x_flatten = sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_flatten,y,test_size=0.3)

In [ ]:
x_train.shape

(6085, 12)

In [ ]:
import tensorflow as tf
import tensorflow.keras as k
from keras.models import Sequential

In [ ]:
model = Sequential([
    k.layers.Dense(24,input_shape=(12,),activation='relu'),
    k.layers.Dense(12,activation='relu'),
    k.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_flatten,y,epochs=100)

Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


272/272 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6784 - loss: 0.6319
Epoch 2/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7435 - loss: 0.5319
Epoch 3/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7552 - loss: 0.5022
Epoch 4/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7656 - loss: 0.4707
Epoch 5/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7748 - loss: 0.4575
Epoch 6/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7743 - loss: 0.4594
Epoch 7/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7849 - loss: 0.4424
Epoch 8/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7804 - loss: 0.4434
Epoch 9/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7895 - loss: 0.4366
Epoch 10/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7951 - loss: 0.4374
Epoch 11/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7948 - loss: 0.4376
Epoch 12/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [ ]:
model.evaluate(x_test,y_test)

82/82 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7836 - loss: 0.4366


[0.42296403646469116, 0.796012282371521]

In [ ]:
predict = model.predict(x_test)

82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [ ]:
predict[2]

array([0.08461315], dtype=float32)

In [ ]:
predicted = []
for i in predict:
  if(i>0.5):
    predicted.append(1)
  else:
    predicted.append(0)

In [ ]:
tf.math.confusion_matrix(y_test,predicted)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1025,  271],
       [ 283, 1029]], dtype=int32)>

In [ ]:
test = pd.read_csv('test.csv')

In [ ]:
PassengerId = test['PassengerId']
test.drop(columns=['PassengerId','Cabin','Name'],inplace=True)

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    4190 non-null   object 
 1   CryoSleep     4184 non-null   object 
 2   Destination   4185 non-null   object 
 3   Age           4277 non-null   float64
 4   VIP           4184 non-null   object 
 5   RoomService   4277 non-null   float64
 6   FoodCourt     4277 non-null   float64
 7   ShoppingMall  4277 non-null   float64
 8   Spa           4277 non-null   float64
 9   VRDeck        4277 non-null   float64
dtypes: float64(6), object(4)
memory usage: 334.3+ KB


In [ ]:
test.isnull().sum()

HomePlanet       87
CryoSleep        93
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
dtype: int64

In [ ]:
col10=[col10 for col10 in test if test[col10].dtypes=='float64']
for i in col10:
    test[i].fillna(test[i].mean(),inplace=True)

<ipython-input-69-3f4028301a18>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test[i].fillna(test[i].mean(),inplace=True)


In [ ]:
col11=[col11 for col11 in test if test[col11].dtypes=='object']
for i in col11:
    test[i].fillna(test[i].mode()[0],inplace=True)

<ipython-input-73-9e597fd006e2>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test[i].fillna(test[i].mode()[0],inplace=True)
<ipython-input-73-9e597fd006e2>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test[i].fillna(test[i].mode()[0],inplace=True)


In [ ]:
test1 = pd.get_dummies(test,columns=col11,drop_first=True)

In [ ]:
test1_flatten = sc.fit_transform(test1)

In [ ]:
Transport=model.predict(test1_flatten)

134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [ ]:
Transported = []
for i in Transport:
  if(i>0.5):
    Transported.append(1)
  else:
    Transported.append(0)

In [ ]:
Transported = pd.DataFrame(Transported)

In [ ]:
pd.concat([PassengerId,Transported],axis=1).to_csv("submission.csv",index=False)